package org.terrytsao.model;

public enum CatVac {
	PANLEUKOPENIA, RHINOTRACHEITIS, CALICIVIRUS, RABIES, FELINE_LEUKEMIA, CHLAMYDOPHILA, FELINE_INFECTIOUS_PERITONITIS, BORDETELLA, GIARDIA, FELINE_IMMUNODEFICIENCY_VIRUS
}
